export { format, createFormatter, stringifyOptions, opaqueHandlers, toMarkdownExtensions } from "./format.js";
export {
  parse,
  createParser,
  micromarkExtensions,
  fromMarkdownExtensions,
} from "./parse.js";
export {
  fnv1a64,
  toBase36,
  contentHash,
  CONTENT_ID_LENGTH,
  FNV_OFFSET_BASIS_64,
  FNV_PRIME_64,
} from "./hash.js";
export {
  blocksOf,
  sectionsOf,
  normalizedText,
  replaceBlock,
  moveBlock,
  moveSection,
  setHeadingDepth,
  type Block,
  type BlockNode,
  type Section,
} from "./blocks.js";

export {
  segmentSentences,
  sentencesOf,
  paragraphText,
  replaceSentence,
  reorderSentences,
  ABBREVIATIONS,
  type Sentence,
  type SentenceRange,
  type SentenceOptions,
  type SegmentOptions,
  type SegmentFn,
} from "./sentences.js";

export {
  fallbackSegment,
  fallbackSentences,
  segmenterSelfTest,
  SEGMENTER_CANARIES,
  type SegmenterCanary,
  type SegmenterChoice,
} from "./segment-fallback.js";

export {
  SIDECAR_VERSION,
  ANCHOR_KINDS,
  COACH_SCOPES,
  SIDECAR_LISTS,
  anchorSchema,
  variantSchema,
  historyEntrySchema,
  headingEntrySchema,
  rewriteEntrySchema,
  coachEntrySchema,
  orphanSchema,
  sidecarSchema,
  parseSidecar,
  emptySidecar,
  candidatesOf,
  candidateAt,
  sorensenDice,
  DICE_THRESHOLD,
  resolveAnchor,
  attach,
  refresh,
  reanchor,
  applyReorderSentences,
  applyMoveSection,
  FRONT_MATTER_KEYS,
  FRONT_MATTER_UNSUPPORTED,
  readFrontMatter,
  writeFrontMatter,
  mirrorFrontMatter,
  type AnchorKind,
  type CoachScope,
  type Anchor,
  type Variant,
  type HistoryEntry,
  type HeadingEntry,
  type RewriteEntry,
  type CoachEntry,
  type SidecarList,
  type Orphan,
  type Sidecar,
  type AnchorCandidate,
  type ResolutionStep,
  type Resolution,
  type ResolveOptions,
  type AttachResolution,
  type AttachResult,
  type DocumentState,
  type FrontMatterKey,
  type FrontMatterUnsupportedReason,
  type FrontMatterQuote,
  type FrontMatterField,
  type FrontMatterUnsupportedField,
  type FrontMatterEntry,
  type FrontMatter,
  type FrontMatterWrite,
} from "./sidecar.js";

export function placeholder(): string {
  return "core";
}
