#!/usr/bin/env node
// assemble-sidecars.ts — task 4.2 (dev-only aarch64 Linux entries added by 4.2's clean-checkout
// repair, principal lesson [4.2] 2026-10-07T17:19:11Z). Takes the artifacts `pnpm fetch-sidecars`
// already verified and extracted into scripts/.cache/sidecars/ (4 platform binaries + 4 macOS
// slices, task 4.1; 2 dev-only aarch64 Linux entries, task 4.2's repair) and produces the 6
// target-suffixed files Tauri's `externalBin` needs in apps/desktop/src-tauri/binaries/: the 4
// platform binaries copied through unchanged, plus `pandoc-universal-apple-darwin` and
// `typst-universal-apple-darwin`, each `lipo -create`d from that tool's two macOS slices.
// src-tauri/binaries/ is gitignored (the files are large and regenerated by this script); there is
// never a `slices` subdirectory under it. The 2 `kind: dev` entries are also copied into
// src-tauri/binaries/ (real binaries, not stand-ins — `tauri_build::try_build` checks for the
// host's own target triple on every `cargo build`/`cargo test`, not only `tauri build`'s bundling
// step) but are never counted among the 6 shipped distributables: aarch64 Linux is not a packaging
// target (PRD §4).
//
// `lipo` only exists on macOS (Apple's own Mach-O fat-binary tool; this container has no
// `lipo`/`llvm-lipo`, checked during this task). Real multi-arch combination therefore only
// happens where `lipo` is actually on PATH (macOS CI, per DECISIONS and the 4.2 ciAcceptance's
// `lipo -info` check); everywhere else, the universal file is a single-slice stand-in (one slice's
// bytes, still executable) so the file is present and `pnpm tauri build` never looks for it on a
// non-macOS target, without claiming a fat binary this host cannot produce. The fallback is taken
// only on `lipo`'s own ENOENT (command not found), not by checking `process.platform`, so a host
// that does carry a working `lipo` always takes the real path.
import { chmodSync, copyFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { loadLock, type SidecarArtifact } from "./fetch-sidecars.ts";

const HERE = dirname(fileURLToPath(import.meta.url));

export interface LipoResult {
  tool: string;
  outPath: string;
  usedRealLipo: boolean;
}

/** Combines `slices` (exactly 2 paths, one per macOS arch) into `outPath`. Returns whether the real
 * `lipo` ran (true) or the single-slice stand-in was written because `lipo` is not on PATH
 * (false). Any other `lipo` failure (a real invocation that exits non-zero) is not swallowed. */
export function lipoCreate(tool: string, slices: [string, string], outPath: string): LipoResult {
  const r = spawnSync("lipo", ["-create", slices[0], slices[1], "-output", outPath]);
  if (r.error && (r.error as NodeJS.ErrnoException).code === "ENOENT") {
    copyFileSync(slices[0], outPath);
    chmodSync(outPath, 0o755);
    return { tool, outPath, usedRealLipo: false };
  }
  if (r.error) throw r.error;
  if (r.status !== 0) {
    throw new Error(`lipo -create ${slices.join(" ")} -output ${outPath} exited ${r.status}: ${r.stderr.toString("utf8")}`);
  }
  chmodSync(outPath, 0o755);
  return { tool, outPath, usedRealLipo: true };
}

export function assembleSidecars(opts: {
  lockPath: string;
  cacheDir: string;
  outDir: string;
}): LipoResult[] {
  const artifacts = loadLock(opts.lockPath);
  mkdirSync(opts.outDir, { recursive: true });

  const missing = artifacts.filter((a) => !existsSync(join(opts.cacheDir, a.target)));
  if (missing.length > 0) {
    throw new Error(
      `missing ${missing.length} sidecar artifact(s) in ${opts.cacheDir} (run \`pnpm fetch-sidecars\` first): ` +
        missing.map((a) => a.target).join(", "),
    );
  }

  for (const artifact of artifacts.filter((a) => a.kind === "binary" || a.kind === "dev")) {
    const dest = join(opts.outDir, artifact.target);
    copyFileSync(join(opts.cacheDir, artifact.target), dest);
    chmodSync(dest, 0o755);
  }

  const results: LipoResult[] = [];
  for (const tool of ["pandoc", "typst"] as const) {
    const slices = artifacts
      .filter((a): a is SidecarArtifact => a.kind === "slice" && a.tool === tool)
      .sort((a, b) => a.target.localeCompare(b.target));
    if (slices.length !== 2) {
      throw new Error(`expected exactly 2 macOS slices for ${tool}, found ${slices.length}`);
    }
    const slicePaths: [string, string] = [
      join(opts.cacheDir, slices[0].target),
      join(opts.cacheDir, slices[1].target),
    ];
    const outPath = join(opts.outDir, `${tool}-universal-apple-darwin`);
    results.push(lipoCreate(tool, slicePaths, outPath));
  }
  return results;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const flag = (name: string, fallback: string) => {
    const i = args.indexOf(name);
    return i === -1 ? fallback : args[i + 1];
  };
  const lockPath = flag("--lock", join(HERE, "sidecars.lock.json"));
  const cacheDir = flag("--cache", join(HERE, ".cache/sidecars"));
  const outDir = flag("--out", join(HERE, "..", "apps/desktop/src-tauri/binaries"));
  const results = assembleSidecars({ lockPath, cacheDir, outDir });
  console.log(`assemble-sidecars: 6 distributables written to ${outDir}`);
  for (const r of results) {
    console.log(
      `assemble-sidecars: ${r.tool} universal binary ${r.usedRealLipo ? "lipo-combined" : "single-slice stand-in (no lipo on PATH)"} at ${r.outPath}`,
    );
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err: unknown) => {
    console.error(`assemble-sidecars: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}
